assign15/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path  route ("/")
  # root "articles#index"
  root to: "sessions#login"
  resources :products do
  get 'search', on: :collection
  end

  resources :users, only: [:new, :create, :update, :edit, :show, :destroy]

  get '/login', to: 'sessions#create'
  post '/login', to: 'sessions#create'
  # post '/logout', to: 'sessions#destroy'
  # get '/logout', to: 'sessions#destroy'

end

assign15/app/models/product.rb
class Product < ApplicationRecord
end

assign15/app/controllers/admin_controller.rb
class AdminController < ApplicationController

  private
  def require_admin
    unless current_user&.role == 'admin'
      redirect_to root_path, alert: "Access denied"
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

assign15/app/controllers/products_controller.rb
class ProductsController < AdminController
  before_action :require_admin, only: [:destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully deleted.'
  end
    
  def search
    @search_query = params[:search_query]
    @products = Product.where("name LIKE ?", "%#{@search_query}%")
  end
  
  private
  
  def search_params
    params.permit(:search_query)
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end

end

assign15/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])
    if @user.present?
      session[:user_id] = @user.id
      redirect_to products_path
    end
    #   if @user.role == "admin"
    #     redirect_to products_path
    #   else
    #     redirect_to products_path
    #   end
    # end
  end
end

assign15/app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :require_admin, except: [:index, :new, :search, :show] 
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
    end
    def show
      @user = User.find(params[:id])
    end
    private
    def user_params
      params.require(:user).permit(:username, :password, :role)
    end
end

assign15/app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= product.name %></li>
    <%= link_to "Delete", product_path(product), data: {turbo_method: :delete} %>
  <% end %>
</ul>

<%= button_to "New Products", new_product_path, method: :get %>

assign15/app/views/products/new.html.erb
<h1>Add products</h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <% end %>

assign15/app/views/products/search.html.erb
<h1>Search Products</h1>

<%= form_tag search_products_path, method: :get do %>
  <%= label_tag :search_query, "Search by product name:" %>
  <%= text_field_tag :search_query, params[:search_query], placeholder: "Enter search query" %>
  <%= submit_tag "Search" %>
<% end %>
<% if @products.any? %>
  <h2>Search Results:</h2>
  
    <% @products.each do |product| %>
      Product : <%= product.name %>
     
    <% end %>
  
<% else %>
  <p>No products found.</p>
<% end %>

assign15/app/views/products/show.html.erb
<p>product_name : <%= @product.name %></p>