assign16/config/routes.rb
Rails.application.routes.draw do
  get '/photos(/:id)', to: 'photos#show'
  resources :photos
  namespace :admin do
    resources :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

assign16/app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

assign16/app/models/admin/user.rb
class Admin::User < ApplicationRecord
end

assign16/app/models/photo.rb
class Photo < ApplicationRecord
end

assign16/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_admin_user, only: %i[ show edit update destroy ]

  # GET /admin/users or /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users or /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_user_url(@admin_user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to admin_user_url(@admin_user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1 or /admin/users/1.json
  def destroy
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_params
      params.require(:admin_user).permit(:name, :email, :phone)
    end
end

assign16/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:name, :description)
    end
end

assign16/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

assign16/app/helpers/photos_helper.rb
module PhotosHelper
end

assign16/app/views/admin/users/_form.html.erb
<%= form_with(model: admin_user) do |form| %>
  <% if admin_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% admin_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

assign16/app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

</div>

assign16/app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Show this user", @admin_user %> |
  <%= link_to "Back to users", admin_users_path %>
</div>

assign16/app/views/admin/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="admin_users">
  <% @admin_users.each do |admin_user| %>
    <%= render admin_user %>
    <p>
      <%= link_to "Show this user", admin_user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_admin_user_path %>

assign16/app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Back to users", admin_users_path %>
</div>

assign16/app/views/admin/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_user %>

<div>
  <%= link_to "Edit this user", edit_admin_user_path(@admin_user) %> |
  <%= link_to "Back to users", admin_users_path %>

  <%= button_to "Destroy this user", @admin_user, method: :delete %>
</div>

assign16/app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

assign16/app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Name:</strong>
    <%= photo.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= photo.description %>
  </p>

</div>

assign16/app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

assign16/app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
    <%= render photo %>
    <p>
      <%= link_to "Show this photo", photo %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

assign16/app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

assign16/app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>