cart/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "products#index"
  get "/carts/add_to_cart", to: "carts#add_to_cart"
  delete "/carts/remove_from_cart", to: "carts#remove_from_cart"
  resources :products
  resources :carts
end

cart/app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items


end

cart/app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :cart
    belongs_to :product

end

cart/app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items
    has_many :carts, through: :cart_items
end

cart/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = session[:cart]
  end

  def add_to_cart
    product_id = params[:product_id]
    cart = session[:cart] || {}
    cart[product_id] = (cart[product_id] || 0) + 1
    session[:cart] = cart
    redirect_to carts_path
  end 

  def remove_from_cart
    product_id = params[:product_id]
    cart = session[:cart] || {}
    # cart[product_id] = (cart[product_id]) - 1
    # if cart[product_id] <= 0
    cart.delete(product_id)
    session[:cart] = cart
    redirect_to root_path
    # end
  end
end

cart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @products=Product.all
      # @products=Product.search(params[:search])
    end 
  
    def show
      @product=Product.find(params[:id]) 
    end
  
    def new 
      @product=Product.new
    end
    
    def create 
      @product=Product.new(product_params)
  
      if @product.save
        redirect_to @product
      else
        render :new
      end
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
  
      if @product.update(product_params)
        redirect_to product_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
  
      redirect_to root_path, status: :see_other
    end
  
   
    private 
    def product_params 
      params.require(:product).permit(:product_name, :price, :discription)
    end
  end

cart/app/helpers/carts_helper.rb
module CartsHelper
end

cart/app/views/carts/index.html.erb
<% cache("products_list") do %>
    <ul>
      <% @cart.each do |product_id, quantity| %>
        <li> <%= Product.find(product_id).product_name %> x <%= quantity %>
          <%= form_tag carts_remove_from_cart_path(product_id: product_id), method: :delete do %>
            <%= submit_tag 'Remove' %>
          <% end %>
        </li>
        <% end %>
    </ul>
  <% end %>

cart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>